const songs=[
{title:'流转之间 · 回响',meta:'未完成的回响 · V1.6',audio:'01-flow.mp3',cover:'01-flow.png',lyric:'01-flow.txt',detail:'flow.html'},
{title:'灯火照长安',meta:'古风叙事 · V1.0',audio:'08-lights.mp3',cover:'08-lights.png',lyric:'08-lights.txt',detail:'lights.html'},
{title:'恰好天晴',meta:'自然民谣 · V1.0',audio:'03-sunny.mp3',cover:'03-sunny.png',lyric:'03-sunny.txt',detail:'sunny.html'},
{title:'风过暗城',meta:'暗城叙事 · V1.0',audio:'06-city.mp3',cover:'06-city.png',lyric:'06-city.txt',detail:'city.html'},
{title:'风从旧站台来',meta:'低声叙事 · V1.0',audio:'02-station.mp3',cover:'02-station.png',lyric:'02-station.txt',detail:'station.html'},
{title:'局中月',meta:'古意叙事 · 双人版 · V1.0',audio:'05-moon-duet.mp3',cover:'05-moon.png',lyric:'05-moon.txt',detail:'moon.html'},
{title:'寻常岁月',meta:'生活叙事 · V1.0',audio:'04-years.mp3',cover:'04-years.png',lyric:'04-years.txt',detail:'years.html'},
{title:'潮落以后',meta:'海岸叙事 · V1.0',audio:'07-tide.mp3',cover:'07-tide.png',lyric:'07-tide.txt',detail:'tide.html'},
{title:'长风不问归期',meta:'长风叙事 · V1.0.1',audio:'10-wind.mp3',cover:'10-wind.png',lyric:'10-wind.txt',detail:'wind.html'},
{title:'几许平生欢',meta:'生命叙事 · V1.2',audio:'09-joy.mp3',cover:'09-joy.png',lyric:'09-joy.txt',detail:'joy.html'},
{title:'山河入梦',meta:'山河叙事 · V1.0',audio:'11-dream.mp3',cover:'11-dream.png',lyric:'11-dream.txt',detail:'dream.html'},
{title:'灯下无声',meta:'古意叙事 · V1.0',audio:'12-lamp.mp3',cover:'12-lamp.png',lyric:'12-lamp.txt',detail:'lamp.html'},
{title:'一脉山风',meta:'山野民谣 · V1.0',audio:'13-mountain.mp3',cover:'13-mountain.png',lyric:'13-mountain.txt',detail:'mountain.html'},
{title:'长夜借我一盏灯',meta:'低声叙事 · V1.1',audio:'14-nightlamp.mp3',cover:'14-nightlamp.png',lyric:'14-nightlamp.txt',detail:'nightlamp.html'},
{title:'青山不渡',meta:'人物叙事 · V1.0',audio:'15-qingshan.mp3',cover:'15-qingshan.png',lyric:'15-qingshan.txt',detail:'qingshan.html'},
{title:'思未央',meta:'纪念叙事 · 54 BPM',audio:'16-siweiyang.mp3',cover:'16-siweiyang.png',lyric:'16-siweiyang.txt',detail:'siweiyang.html'},
{title:'请阁下，入画',meta:'古风叙事 · V1.0',audio:'17-ruhua.mp3',cover:'17-ruhua.png',lyric:'17-ruhua.txt',detail:'ruhua.html'},
{title:'一梦不知年',meta:'古意叙事 · V1.0',audio:'18-yimeng.mp3',cover:'18-yimeng.png',lyric:'18-yimeng.txt',detail:'yimeng.html'},
{title:'海天之外',meta:'海天叙事 · V1.8-3',audio:'19-haitian.mp3',cover:'19-haitian.png',lyric:'19-haitian.txt',detail:'haitian.html'},
{title:'微醺de旧唱片',meta:'旧唱片叙事 · V1.1',audio:'20-weixun.mp3',cover:'20-weixun.png',lyric:'20-weixun.txt',detail:'weixun.html'},
{title:'无言',meta:'低声叙事 · V1.2',audio:'21-wuyan.mp3',cover:'21-wuyan.png',lyric:'21-wuyan.txt',detail:'wuyan.html'}];
const $=s=>document.querySelector(s);const noteByTitle={'流转之间 · 回响':'我把没说的话，藏进掌心的纹路上','灯火照长安':'一盏灯照过长街，也照见没有被看见的人','恰好天晴':'雨停之后，人与日常重新靠近','风过暗城':'风从不明亮的城里穿过','风从旧站台来':'风经过旧站台，也经过没有说完的停留','局中月':'月光照见局中人，也照见局外的沉默','寻常岁月':'普通日子里，时间真正留下的重量','潮落以后':'退潮之后，沙滩才显出真正的形状','长风不问归期':'不必急着抵达的远行','几许平生欢':'活着的人也需要被相逢与陪伴托住','山河入梦':'山河入梦，风物与旧时光在旋律中相逢','灯下无声':'一盏灯下，写没有被说出的沉默','一脉山风':'一脉山风穿过山野，也穿过人的来处','长夜借我一盏灯':'在长夜里借一盏灯，照见仍要继续的人','青山不渡':'青山不渡，留下人物与命运之间的回望','思未央':'思念未央，把告别放回仍在生活的人间','请阁下，入画':'请入画中，让人物、山水与旧事慢慢显形','一梦不知年':'一梦醒来不知年，时间留下未完的回声','海天之外':'海天之外仍有光，风与潮水把远方托起','微醺de旧唱片':'旧唱片转动时，时间和记忆重新靠近','无言':'无言并非空白，沉默里仍有未尽的回响'};const descByTitle={'山河入梦':'让山河、旧梦与远行的脚步在一段旋律里彼此照见。','灯下无声':'把灯下没有说出的情绪交给低声叙述，让沉默保持重量。','一脉山风':'从山风与行路写起，让自然的开阔托住人的心事。','长夜借我一盏灯':'在漫长黑夜里借一盏灯，写仍然选择继续走下去的人。','青山不渡':'让青山、人物与命运之间的距离留在不急着解释的余韵里。','思未央':'把思念放回时间和日常，不把告别推向戏剧性的终点。','请阁下，入画':'以入画为引，让人物和山水在古意的留白中渐次展开。','一梦不知年':'一梦醒来已不知年，旋律保存时间带走又留下的痕迹。','海天之外':'写海天、风浪与远方，让辽阔景色托住低声的叙述。','微醺de旧唱片':'借一张旧唱片写时间回转，也写记忆里仍未散去的温度。','无言':'不把沉默解释成答案，让未说出口的部分自行留下回声。'};let selected=0,page=0,pageSize=10,mode='order',queue=songs.map((_,i)=>i),lyricText='',lyricLines=[],selectToken=0,pendingSeek=null,audioObjectUrl="";
function cleanLyrics(text){return text.split(/\r?\n/).filter(line=>!/^[ \t]*`/.test(line)&&!/^[ \t]*#\s+/.test(line)&&!/^[ \t]*[【\[]\s*(verse|chorus|bridge|intro|outro|pre-chorus|break|spoken|final chorus)\b.*[】\]]\s*$/i.test(line)&&!/^[ \t]*\[[^\]]+\]\s*$/.test(line)&&!/^[《「].*[》」]\s*$/.test(line)).join('\n').trim()}
function parseLyrics(text){return text.split(/\r?\n/).map((line,index)=>{const m=line.match(/^\[(\d+):(\d+(?:\.\d+)?)\]/);return m?{time:Number(m[1])*60+Number(m[2]),index}:null}).filter(Boolean)}
function renderLyrics(){const active=lyricLines.reduce((x,l)=>l.time<=player.currentTime?l:x,null);lyrics.textContent=lyricText.split(/\r?\n/).map((line,i)=>active&&i===active.index?'▶ '+line.replace(/^\[\d+:\d+(?:\.\d+)?\]/,''):line).join('\n')}
async function loadLyrics(s){try{const local=location.protocol==='file:'&&window.lyricDataV3&&window.lyricDataV3[s.lyric];lyricText=cleanLyrics(local||await (await fetch('preview_assets/'+s.lyric)).text());lyricLines=parseLyrics(lyricText);renderLyrics()}catch{lyricText='歌词暂时无法加载。';lyrics.textContent=lyricText}}
function card(s,i){return `<button class="song" type="button" data-index="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="mini-disc"></span><h3>${s.title}</h3><small>${s.meta}</small><span class="lyric-preview">${s.snippet||noteByTitle[s.title]||'作品创作札记，正在整理。'}</span><span class="sound"><i></i><i></i><i></i><i></i></span></button>`}
function preview(kind,start){const a=songs[start],b=songs[start+1],c=songs[start+2];if(kind==='end'||!a)return `<div class="song chapter-end"><span class="num">∞</span><h3>创作中，敬请期待...</h3><small>新的作品正在路上</small><span class="lyric-preview">精彩继续...</span></div>`;return `<button class="song chapter-preview" type="button" data-page="${kind==='next'?page+1:page-1}"><span class="num">${kind==='next'?'→':'↖'}</span><h3>${kind==='next'?'展开新篇章':'返回上一章'}</h3><small>${kind==='next'?'下一页预览':'上一页预览'}</small><span class="lyric-preview">${a.title}<br>${b.title}<br>${c.title}<br>...</span><span class="sound">${kind==='next'?'展开下一章':'继续返回'}</span></button>`}
function renderPage(){const totalPages=Math.ceil(songs.length/9);const start=page===0?0:9+(page-1)*8;const count=page===0?Math.min(9,songs.length):Math.min(8,songs.length-start);let html=page?preview('prev',Math.max(0,start-3)):'';songs.slice(start,start+count).forEach((s,i)=>html+=card(s,start+i));html+=start+count<songs.length?preview('next',start+count):preview('end',0);grid.innerHTML=html;$('#pageLabel').textContent=`${String(page+1).padStart(2,'0')} / ${String(totalPages).padStart(2,'0')}`;$('#homePage').disabled=page===0;$('#prevPage').disabled=page===0;$('#nextPage').disabled=page>=totalPages-1}
async function selectSong(i,autoplay=true){const token=++selectToken;selected=i;const s=songs[i];document.querySelectorAll('.song[data-index]').forEach(x=>x.classList.toggle('active',Number(x.dataset.index)===i));title.textContent=s.title;meta.textContent=s.meta;$('#recordTitle').textContent=s.title;$('#recordMeta').textContent=s.meta;desc.textContent=s.desc||descByTitle[s.title]||'声音、歌词与创作时的微光，在这里保存为一段仍在回响的作品档案。';coverImage.src='preview_assets/'+s.cover;coverImage.alt=s.title+'封面';download.href='preview_assets/'+s.audio;download.download=s.title+'.mp3';detailLink.href='detail/'+s.detail;lyrics.classList.add('open');lyricsBtn.textContent='收起歌词 −';player.pause();player.src='preview_assets/'+s.audio;player.load();await loadLyrics(s);if(token!==selectToken)return;if(autoplay)player.play().catch(()=>{})}
function nextSong(){const pos=queue.indexOf(selected);let n=mode==='random'?queue[Math.floor(Math.random()*queue.length)]:queue[(pos+1)%queue.length];selectSong(n)}
function goPage(next){if(next===page)return;archive.classList.remove('page-forward','page-back');archive.classList.add(next>page?'page-forward':'page-back','page-transitioning');setTimeout(()=>{page=next;renderPage();archive.classList.remove('page-transitioning');archive.classList.add('page-settled');setTimeout(()=>archive.classList.remove('page-settled'),30)},360)}grid.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){goPage(Number(p.dataset.page));return}const c=e.target.closest('[data-index]');if(c)selectSong(Number(c.dataset.index))});$('#homePage').onclick=()=>goPage(0);$('#prevPage').onclick=()=>{if(page)goPage(page-1)};$('#nextPage').onclick=()=>{if(page<Math.ceil(songs.length/9)-1)goPage(page+1)};lyricsBtn.onclick=()=>{lyrics.classList.toggle('open');lyricsBtn.textContent=lyrics.classList.contains('open')?'收起歌词 −':'查看歌词 ＋'};player.addEventListener('timeupdate',renderLyrics);player.addEventListener('ended',nextSong);$('#prevSong').onclick=()=>selectSong(queue[(queue.indexOf(selected)-1+queue.length)%queue.length]);$('#nextSong').onclick=nextSong;$('#modeToggle').onclick=()=>{mode=mode==='order'?'random':'order';$('#modeToggle').textContent=mode==='order'?'↝':'☷';$('#modeToggle').title=mode==='order'?'顺序播放':'随机播放'};$('#singleToggle').onclick=()=>{player.loop=!player.loop;$('#singleToggle').classList.toggle('active',player.loop)};$('#listToggle').onclick=()=>{player.loop=false;mode='order';$('#modeToggle').textContent='↝';$('#modeToggle').title='列表循环'};renderPage();selectSong(0,false);const record=$('.hero-record');player.addEventListener('play',()=>record?.classList.add('is-playing'));player.addEventListener('pause',()=>record?.classList.remove('is-playing'));player.addEventListener('ended',()=>record?.classList.remove('is-playing'));











