const songs=[
{title:'流转之间 · 回响',meta:'未完成的回响 · V1.6',audio:'preview_assets/01-flow.mp3',lyric:'preview_assets/01-flow.txt',cover:'preview_assets/01-flow.png',desc:'以水波、回声和时间的回旋承载一段尚未抵达终点的叙事。声音不急着解释，只留下向前流动的痕迹。'},
{title:'灯火照长安',meta:'古风叙事 · V1.0',audio:'preview_assets/08-lights.mp3',lyric:'preview_assets/08-lights.txt',cover:'preview_assets/08-lights.png',desc:'灯火、长街与一个仍在奔走的人。把历史的远景收进脚步与灯影，写一段不喧哗的坚持。'},
{title:'恰好天晴',meta:'自然民谣 · V1.0',audio:'preview_assets/03-sunny.mp3',lyric:'preview_assets/03-sunny.txt',cover:'preview_assets/03-sunny.png',desc:'不是宏大的答案，只是一场雨后恰好放晴。轻一点的旋律，让人与日常重新靠近。'},
{title:'风过暗城',meta:'暗城叙事 · V1.0',audio:'preview_assets/06-city.mp3',lyric:'preview_assets/06-city.txt',cover:'preview_assets/06-city.png',desc:'风从一座不明亮的城里穿过，带走喧哗，只留下人物心里的暗纹与未竟之事。'},
{title:'风从旧站台来',meta:'低声叙事 · V1.0',audio:'preview_assets/02-station.mp3',lyric:'preview_assets/02-station.txt',cover:'preview_assets/02-station.png',desc:'风经过旧站台，也经过记忆里那些没有被说完的停留。歌曲保持民谣式的留白与慢速呼吸。'},
{title:'局中月',meta:'古意叙事 · 单人版',audio:'preview_assets/05-moon.mp3',lyric:'preview_assets/05-moon.txt',cover:'preview_assets/05-moon.png',desc:'月光照见局中人，也照见局外的沉默。人物、命运与选择在一轮冷月下彼此映照。'},
{title:'寻常岁月',meta:'生活叙事 · V1.0',audio:'preview_assets/04-years.mp3',lyric:'preview_assets/04-years.txt',cover:'preview_assets/04-years.png',desc:'把情绪放回饭桌、灯影和一段段普通日子里。寻常不是平淡，而是时间真正留下的重量。'},
{title:'潮落以后',meta:'海岸叙事 · V1.0',audio:'preview_assets/07-tide.mp3',lyric:'preview_assets/07-tide.txt',cover:'preview_assets/07-tide.png',desc:'潮水退去之后，沙滩才显出真正的形状。歌曲写退潮后的安静，也写人如何与自己的旧日相处。'},
{title:'长风不问归期',meta:'长风叙事 · V1.0.1',audio:'preview_assets/10-wind.mp3',lyric:'preview_assets/10-wind.txt',cover:'preview_assets/10-wind.png',desc:'长风不问归期，像一种不必急着抵达的选择。让辽阔的风景托住低声的叙述，留下远行的余韵。'},
{title:'几许平生欢',meta:'生命叙事 · V1.2',audio:'preview_assets/09-joy.mp3',lyric:'preview_assets/09-joy.txt',cover:'preview_assets/09-joy.png',desc:'活着的人也需要破地狱。歌曲不把告别推向戏剧高潮，而是回到相逢、陪伴与继续生活。'}];
const snippets=['我把没说的话 / 藏进掌心的纹路上','那天的雨落得很轻 / 像一句没有说完的话','有些人长留心头 / 有些人只梦中回眸','家里的钟慢了几分钟 / 谁也没有调好','人走局中，局映人相 / 半生追问，不问归乡','城门之外，风过千年 / 谁将姓名，写入尘烟','多少话咽进喉咙 / 多少年走成了河','也曾把满城风雪 / 收进一身黄昏','风把沉默吹得很轻 / 你没说完的话，我只想静静听','写着人间不该只剩成败 / 只求辛苦的人，能把饭吃完'];
const $=s=>document.querySelector(s),grid=$('#grid'),title=$('#title'),meta=$('#meta'),desc=$('#desc'),player=$('#player'),download=$('#download'),cover=$('#cover'),coverImage=$('#coverImage'),recordTitle=$('#recordTitle'),recordMeta=$('#recordMeta'),lyrics=$('#lyrics'),lyricsBtn=$('#lyricsBtn'),record=$('.hero-record');
const audioBase='https://raw.githubusercontent.com/AaronZHAO84/music-portfolio/main/preview_assets/';
const imageBase='https://raw.githubusercontent.com/AaronZHAO84/music-portfolio/main/preview_assets/';
let audioObjectUrl='';
let selectedIndex=-1,lyricLines=[],lyricText='';
grid.innerHTML=songs.map((s,i)=>`<button class="song" data-index="${i}" type="button"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="mini-disc"></span><h3>${s.title}</h3><small>${s.meta}</small><span class="lyric-preview">${snippets[i]}</span><span class="sound"><i></i><i></i><i></i><i></i></button>`).join('');
function parseLyrics(text){return text.split(/\r?\n/).map((line,index)=>{const m=line.match(/^\[(\d+):(\d+(?:\.\d+)?)\](.*)$/);return m?{time:Number(m[1])*60+Number(m[2]),index}:null}).filter(Boolean)}
function renderLyrics(){if(!lyricText)return;const active=lyricLines.reduce((last,line)=>line.time<=player.currentTime?line:last,null);lyrics.textContent=lyricText.split(/\r?\n/).map((line,index)=>active&&index===active.index?'▶ '+line.replace(/^\[\d+:\d+(?:\.\d+)?\]/,''):line).join('\n');}
async function loadLyrics(song){lyricText='';lyricLines=[];lyrics.textContent='歌词加载中…';try{const r=await fetch(song.lyric);if(!r.ok)throw Error();lyricText=await r.text();lyricLines=parseLyrics(lyricText);renderLyrics();}catch{lyrics.textContent='歌词预览暂时无法加载。发布时请将歌词文件与网页一同上传。';}}
async function selectSong(index){const song=songs[index];if(index===selectedIndex){togglePlayback();return;}selectedIndex=index;document.querySelectorAll('.song').forEach((el,n)=>el.classList.toggle('active',n===index));title.textContent=song.title;meta.textContent=song.meta;desc.textContent=song.desc;recordTitle.textContent=song.title;recordMeta.textContent=song.meta;player.pause();const audioUrl=audioBase+song.audio.split('/').pop();download.href=audioUrl;download.download=`${song.title}.mp3`;coverImage.src=imageBase+(song.cover?song.cover.split('/').pop():'cover_background_v1.png');coverImage.alt=`${song.title} 封面`;cover.querySelector('.cover-mark').textContent=song.cover?'COVER / A · Z':'A · Z / WORK';lyrics.classList.remove('open');lyricsBtn.textContent='查看歌词 ＋';await loadLyrics(song);try{const response=await fetch(audioUrl);if(!response.ok)throw Error();const blob=await response.blob();if(audioObjectUrl)URL.revokeObjectURL(audioObjectUrl);audioObjectUrl=URL.createObjectURL(blob);player.src=audioObjectUrl;player.load();await player.play();}catch{player.src=audioUrl;player.load();player.play().catch(()=>{});}}
download.addEventListener('click',async e=>{e.preventDefault();if(selectedIndex<0)return;const audioUrl=audioBase+songs[selectedIndex].audio.split('/').pop();try{const r=await fetch(audioUrl);if(!r.ok)throw Error();const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${songs[selectedIndex].title}.mp3`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{window.open(audioUrl,'_blank');}});
function togglePlayback(){if(selectedIndex<0){selectSong(0);return;}player.paused?player.play().catch(()=>{}):player.pause();}
grid.addEventListener('click',e=>{const card=e.target.closest('.song');if(card)selectSong(Number(card.dataset.index));});record.addEventListener('click',togglePlayback);lyricsBtn.addEventListener('click',()=>{lyrics.classList.toggle('open');lyricsBtn.textContent=lyrics.classList.contains('open')?'收起歌词 −':'查看歌词 ＋';});player.addEventListener('play',()=>record.classList.add('is-playing'));player.addEventListener('pause',()=>record.classList.remove('is-playing'));player.addEventListener('ended',()=>record.classList.remove('is-playing'));player.addEventListener('timeupdate',renderLyrics);let resumeTime=0,resuming=false;player.addEventListener('stalled',()=>{if(!player.src||player.paused||resuming)return;resumeTime=player.currentTime;resuming=true;player.load();});player.addEventListener('loadedmetadata',()=>{if(!resuming)return;player.currentTime=resumeTime;resuming=false;player.play().catch(()=>{});});player.addEventListener('waiting',()=>record.classList.remove('is-playing'));player.addEventListener('canplay',()=>{if(!player.paused)record.classList.add('is-playing');});selectSong(0);
