var base='../assets/';var songs={
lights:{n:'02',title:'灯火照长安',sub:'一盏殿灯，照见制度深处未被听见的人',audio:'08-lights.mp3',cover:'08-lights.png',lyric:'08-lights.txt',form:'Chinese Cinematic Mandopop',tempo:'Slow 6/8 · 76 BPM',tone:'Low Piano · Cello · Erhu · Xiao',voice:'Dignified · Intimate · Clear',style:'Chinese cinematic mandopop with restrained ancient-court atmosphere; low piano, cello, erhu color and wide but elegant strings.',context:'从宫墙、奏章、粮仓与长街的空间对照出发，把宏大的历史压力落到一个个仍在奔走的人身上。歌曲不复述史实，而让殿灯照出“天下被听见，却没有真正被看见”的沉默。'},
sunny:{n:'03',title:'恰好天晴',sub:'雨停之后，人与日常重新靠近',audio:'03-sunny.mp3',cover:'03-sunny.png',lyric:'03-sunny.txt',form:'Elegant Chinese Pop Ballad',tempo:'Relaxed 4/4 · 72 BPM',tone:'Warm Piano · Acoustic Guitar · Brushed Drums',voice:'Sincere · Conversational · Light',style:'Understated cinematic warmth, lightly playful surface, warm piano, acoustic guitar harmonics and muted strings.',context:'写一场雨后的放晴，也写那些不必被命名的轻松时刻。伞、咖啡、站台钟与窗边花朵让情绪自然浮出，不直接解释难过，只让日常自己发亮。'},
city:{n:'04',title:'风过暗城',sub:'风从不明亮的城里穿过',audio:'06-city.mp3',cover:'06-city.png',lyric:'06-city.txt',form:'Chinese Narrative Folk-Pop',tempo:'Slow · Restrained Pulse',tone:'Low Strings · Piano · Room Ambience',voice:'Weathered · Calm · Narrative',style:'Dark cinematic folk-pop, intimate narrative vocal, low strings and room ambience with restrained tension.',context:'城市不是背景，而是一层压在人物身上的暗色纹理。风带走喧哗，留下未竟之事；歌曲让阴影停留，却不把人物推向夸张的悲剧。'},
station:{n:'05',title:'风从旧站台来',sub:'风经过旧站台，也经过记忆里没有说完的停留',audio:'02-station.mp3',cover:'02-station.png',lyric:'02-station.txt',form:'Mandarin Acoustic Folk',tempo:'Slow · Spacious',tone:'Acoustic Guitar · Soft Piano · Air',voice:'Close · Natural · Unforced',style:'Intimate acoustic folk with spacious pauses, gentle guitar, soft piano and a quiet sense of departure without stating it directly.',context:'旧站台承载的不是一次明确的离开，而是许多停留过后仍未说尽的话。风是唯一持续移动的事物，让记忆保持开放，不被一句结论封住。'},
moon:{n:'06',title:'局中月',sub:'月光照见局中人，也照见局外的沉默',audio:'05-moon.mp3',cover:'05-moon.png',lyric:'05-moon.txt',form:'Chinese Ancient-Style Narrative',tempo:'Slow 6/8 · Moonlit Pace',tone:'Xiao · Guqin Texture · Low Strings',voice:'Dual · Restrained · Reflective',style:'Moonlit Chinese narrative ballad, two contrasting voices, xiao and guqin-like textures, spacious low strings.',context:'一轮冷月把人物与命运同时照亮。双人声线不是简单对唱，而像局中人与局外人彼此映照，让选择在沉默之间渐次显形。'},
years:{n:'07',title:'寻常岁月',sub:'普通日子里，时间真正留下的重量',audio:'04-years.mp3',cover:'04-years.png',lyric:'04-years.txt',form:'Warm Chinese Narrative Folk-Pop',tempo:'Relaxed 4/4 · Walking Pulse',tone:'Acoustic Guitar · Piano · Warm Strings',voice:'Plainspoken · Earthy · Warm',style:'Warm narrative folk-pop, relaxed walking pulse, acoustic guitar, soft piano, brushed drums and gentle communal warmth.',context:'把情绪放回饭桌、灯影与一段段普通日子里。歌曲相信寻常并不等于平淡，真正的重量藏在重复的生活动作和没有被郑重说出的照料里。'},
tide:{n:'08',title:'潮落以后',sub:'退潮之后，沙滩才显出真正的形状',audio:'07-tide.mp3',cover:'07-tide.png',lyric:'07-tide.txt',form:'Mandarin Cinematic Folk-Pop',tempo:'Slow 6/8 · 72 BPM',tone:'Acoustic Guitar · Sparse Piano · Cello',voice:'Calm · Weathered · Open',style:'Slow restrained coastal folk-pop, acoustic guitar, sparse piano, subtle cello and a final return to solitary strings.',context:'潮水退去并不意味着故事结束，反而让被遮住的形状慢慢显现。歌曲写人与旧日相处的过程：不急着和解，只在安静里辨认自己留下的轮廓。'},
wind:{n:'09',title:'长风不问归期',sub:'不必急着抵达的远行',audio:'10-wind.mp3',cover:'10-wind.png',lyric:'10-wind.txt',form:'Chinese Guofeng Narrative Pop',tempo:'Moderate · Open Road Pulse',tone:'Piano · Acoustic Guitar · Xiao · Low Strings',voice:'Natural · Determined · Compassionate',style:'Chinese guofeng narrative pop, piano, acoustic guitar, low strings and xiao; dignified but never imperial.',context:'长风不替人询问终点，只把路上的灯、雨、山与脚步一一托住。歌曲写远行，也写一种不必急着证明自己的选择，让辽阔景色服务于普通人的叙述。'},
joy:{n:'10',title:'几许平生欢',sub:'活着的人，也需要被相逢与陪伴托住',audio:'09-joy.mp3',cover:'09-joy.png',lyric:'09-joy.txt',form:'Mandarin Cinematic Folk-Pop Ballad',tempo:'Slow 6/8 · 74 BPM',tone:'Felt Piano · Acoustic Guitar · Cello · Strings',voice:'Warm · Restrained · Human',style:'Mandarin cinematic folk-pop ballad, slow 6/8, felt piano, acoustic guitar, cello and gradually expanding strings.',context:'歌曲不把告别推向戏剧高潮，而把目光留给仍在生活的人：相逢、陪伴、承担，以及在漫长日子里重新找到一点欢喜。'},
};
songs.flow={n:'01',title:'流转之间 · 回响',sub:'当沉默和心跳落在同一拍上，未说完的仍在光影之间流转',audio:'01-flow.mp3',cover:'01-flow.png',lyric:'01-flow.txt',form:'Chinese Cinematic Adult-Contemporary',tempo:'Slow 6/8 · 80 BPM',tone:'Felt Piano · Cello · Organic Drum · Low Strings',voice:'Warm · Steady · Clear',style:'Chinese cinematic adult-contemporary with a short piano and cello hook, intimate verses, brighter choruses and natural narrative phrasing.',context:'从黄昏窗边的一束光起笔，歌曲经过潮水、长廊、叶脉、月光与熄灯后的星群，把未说完的话交给风与河流。回响不是返回过去，而是在同一束光里重新获得继续向前的力量。'};
Object.assign(songs,{lights:{intro:'把殿灯、长街与粮仓放在同一片夜色里，写那些被天下听见、却没有真正被看见的人。'},sunny:{intro:'从一场雨后的放晴出发，把伞、咖啡、站台钟和窗边花朵交给旋律，让日常在不经意间重新发亮。'},city:{intro:'让风穿过一座不明亮的城，带走喧哗，留下人物心里没有说尽的暗纹与仍未结束的事情。'},station:{intro:'旧站台不是离别的答案，而是一处让记忆停留的地方；风从那里来，也把没有说完的话带向更远处。'},moon:{intro:'借一轮冷月照见局中人的选择，也照见局外的沉默，让两道声线在命运的缝隙里彼此映照。'},years:{intro:'把歌写回饭桌、灯影和一段段普通日子，去听那些没有被郑重说出的照料，如何成为时间留下的重量。'},tide:{intro:'潮水退去之后，沙滩才显出真正的形状；这首歌写人与旧日相处时，那段不急着和解的安静过程。'},wind:{intro:'长风不问归期，只托住远行路上的灯、雨与山；这首歌写一种不必急着证明自己的选择。'},joy:{intro:'把目光留给仍在生活的人：相逢、陪伴、承担，以及在漫长日子里重新找到一点可以握住的欢喜。'}});
Object.assign(songs.lights,{n:'02',audio:'08-lights.mp3',cover:'08-lights.png',lyric:'08-lights.txt',form:'Chinese Cinematic Mandopop',tempo:'Slow 6/8 · 76 BPM',tone:'Low Piano · Cello · Erhu · Xiao',voice:'Dignified · Intimate · Clear'});Object.assign(songs.sunny,{n:'03',audio:'03-sunny.mp3',cover:'03-sunny.png',lyric:'03-sunny.txt',form:'Elegant Chinese Pop Ballad',tempo:'Relaxed 4/4 · 72 BPM',tone:'Warm Piano · Acoustic Guitar · Brushed Drums',voice:'Sincere · Conversational · Light'});Object.assign(songs.city,{n:'04',audio:'06-city.mp3',cover:'06-city.png',lyric:'06-city.txt',form:'Chinese Narrative Folk-Pop',tempo:'Slow · Restrained Pulse',tone:'Low Strings · Piano · Room Ambience',voice:'Weathered · Calm · Narrative'});Object.assign(songs.station,{n:'05',audio:'02-station.mp3',cover:'02-station.png',lyric:'02-station.txt',form:'Mandarin Acoustic Folk',tempo:'Slow · Spacious',tone:'Acoustic Guitar · Soft Piano · Air',voice:'Close · Natural · Unforced'});Object.assign(songs.moon,{n:'06',audio:'05-moon.mp3',cover:'05-moon.png',lyric:'05-moon.txt',form:'Chinese Ancient-Style Narrative',tempo:'Slow 6/8 · Moonlit Pace',tone:'Xiao · Guqin Texture · Low Strings',voice:'Dual · Restrained · Reflective'});Object.assign(songs.years,{n:'07',audio:'04-years.mp3',cover:'04-years.png',lyric:'04-years.txt',form:'Warm Chinese Narrative Folk-Pop',tempo:'Relaxed 4/4 · Walking Pulse',tone:'Acoustic Guitar · Piano · Warm Strings',voice:'Plainspoken · Earthy · Warm'});Object.assign(songs.tide,{n:'08',audio:'07-tide.mp3',cover:'07-tide.png',lyric:'07-tide.txt',form:'Mandarin Cinematic Folk-Pop',tempo:'Slow 6/8 · 72 BPM',tone:'Acoustic Guitar · Sparse Piano · Cello',voice:'Calm · Weathered · Open'});Object.assign(songs.wind,{n:'09',audio:'10-wind.mp3',cover:'10-wind.png',lyric:'10-wind.txt',form:'Chinese Guofeng Narrative Pop',tempo:'Moderate · Open Road Pulse',tone:'Piano · Acoustic Guitar · Xiao · Low Strings',voice:'Natural · Determined · Compassionate'});Object.assign(songs.joy,{n:'10',audio:'09-joy.mp3',cover:'09-joy.png',lyric:'09-joy.txt',form:'Mandarin Cinematic Folk-Pop Ballad',tempo:'Slow 6/8 · 74 BPM',tone:'Felt Piano · Acoustic Guitar · Cello · Strings',voice:'Warm · Restrained · Human'});
Object.assign(songs.flow,{archive:'从黄昏窗边的一束光开始，风、潮水、长廊、叶脉与月光把情绪逐层推远；这份记录保存一首歌如何把未说完的话，流向同一束光里的重新听见。'});Object.assign(songs.lights,{archive:'从殿灯与长街的明暗对照进入历史深处，奏章、粮仓和奔走的人构成歌曲的现实重量；声音克制，却让被忽略的人始终在场。'});Object.assign(songs.sunny,{archive:'把雨后的轻亮放进伞、咖啡、站台钟和窗边花朵之间，旋律不急着总结人生，只让一个普通下午重新靠近人的心。'});Object.assign(songs.city,{archive:'让风穿过一座不明亮的城，带走表面的喧哗，留下人物心里未竟的暗纹；低声的叙述因此比直接的宣告更有重量。'});Object.assign(songs.station,{archive:'旧站台保存着停留而非结论，风从那里经过，把没有说完的话带向远处；歌曲以留白和慢速呼吸，让记忆保有继续发生的可能。'});Object.assign(songs.moon,{archive:'一轮冷月同时照见局中人的选择与局外的沉默，两道声线彼此映照，让命运不靠解释推进，而在迟疑与凝望之间显形。'});Object.assign(songs.years,{archive:'把歌放回饭桌、灯影和日常的重复动作里，记录那些不被郑重说出的照料；所谓寻常，正是时间最可靠的回声。'});Object.assign(songs.tide,{archive:'潮水退去后，沙滩才露出真实形状；歌曲把人与旧日相处的过程留在安静里，不强行和解，也不把遗憾说成答案。'});Object.assign(songs.wind,{archive:'长风托住远行路上的灯、雨与山，却不替人追问归期；歌曲写一种不急着证明自己的选择，让辽阔风景服务于普通人的叙述。'});Object.assign(songs.joy,{archive:'把目光留给仍在生活的人，从相逢、陪伴与承担里寻找一点可以握住的欢喜；告别不被推向高潮，而被放回持续的日子。'});
songs.flow.archive='从黄昏窗边的一束光开始，风、潮水、长廊、叶脉与月光把情绪逐层推远；这份记录保存一首歌如何把未说完的话，流向同一束光里的重新听见。';
Object.assign(songs.lights,{context:'从宫墙、奏章、粮仓与长街的空间对照出发，把宏大的历史压力落到一个个仍在奔走的人身上。歌曲不复述史实，而让殿灯照出“天下被听见，却没有真正被看见”的沉默。'});
Object.assign(songs.sunny,{context:'写一场雨后的放晴，也写那些不必被命名的轻松时刻。伞、咖啡、站台钟与窗边花朵让情绪自然浮出，不直接解释难过，只让日常自己发亮。'});
Object.assign(songs.city,{context:'城市不是背景，而是一层压在人物身上的暗色纹理。风带走喧哗，留下未竟之事；歌曲让阴影停留，却不把人物推向夸张的悲剧。'});
Object.assign(songs.station,{context:'旧站台承载的不是一次明确的离开，而是许多停留过后仍未说尽的话。风是唯一持续移动的事物，让记忆保持开放，不被一句结论封住。'});
Object.assign(songs.moon,{context:'一轮冷月把人物与命运同时照亮。双人声线不是简单对唱，而像局中人与局外人彼此映照，让选择在沉默之间渐次显形。'});
Object.assign(songs.years,{context:'把情绪放回饭桌、灯影与一段段普通日子里。歌曲相信寻常并不等于平淡，真正的重量藏在重复的生活动作和没有被郑重说出的照料里。'});
Object.assign(songs.tide,{context:'潮水退去并不意味着故事结束，反而让被遮住的形状慢慢显现。歌曲写人与旧日相处的过程：不急着和解，只在安静里辨认自己留下的轮廓。'});
Object.assign(songs.wind,{context:'长风不替人询问终点，只把路上的灯、雨、山与脚步一一托住。歌曲写远行，也写一种不必急着证明自己的选择，让辽阔景色服务于普通人的叙述。'});
Object.assign(songs.joy,{context:'歌曲不把告别推向戏剧高潮，而把目光留给仍在生活的人：相逢、陪伴、承担，以及在漫长日子里重新找到一点欢喜。'});
Object.assign(songs.lights,{title:'灯火照长安',sub:'一盏殿灯，照见制度深处未被听见的人'});
Object.assign(songs.sunny,{title:'恰好天晴',sub:'雨停之后，人与日常重新靠近'});
Object.assign(songs.city,{title:'风过暗城',sub:'风从不明亮的城里穿过'});
Object.assign(songs.station,{title:'风从旧站台来',sub:'风经过旧站台，也经过记忆里没有说完的停留'});
Object.assign(songs.moon,{title:'局中月',sub:'月光照见局中人，也照见局外的沉默'});
Object.assign(songs.years,{title:'寻常岁月',sub:'普通日子里，时间真正留下的重量'});
Object.assign(songs.tide,{title:'潮落以后',sub:'退潮之后，沙滩才显出真正的形状'});
Object.assign(songs.wind,{title:'长风不问归期',sub:'不必急着抵达的远行'});
Object.assign(songs.joy,{title:'几许平生欢',sub:'活着的人，也需要被相逢与陪伴托住'});
Object.assign(songs.moon,{audio:'05-moon-duet.mp3'});
